FORMAT: 1A
HOST: http://efactor.nickotter.com/api


#EFactor
RESTFull API for *EFactor*.

##Group WorkSession

##WorkSession [/worksession/{id}]

The WorkSession resource has the following attributes

- id
- start
- end
- note

+ Parameters
    + id (string) ... ID of the WorkSession
    
+ Model

    JSON representation of a Work Session

    + Body
        
            {
                "_id" : ObjectId("52dcb465231dab2b52000002"),
                "start" : ISODate("2014-01-19T20:30:00Z"),
                "end" : ISODate("2014-01-19T23:00:00Z"),
                "note" : "Because TEST",
                "user_id" : ObjectId("52dcb38c231dab0f97000001") 
            }

### Retrieve a Single Work Session [GET]
+ Response 200
    
    [WorkSession][]

### Adding a Work Session [PUT]

+ Request (application/json)

        {
            "start": "2014-01-21 11:00",
            "end": "2014-01-21 13:59"
            "note": "I ended because of a phone call"
        }

+ Response 200

##WorkSession Collection [/worksession/]

### Create a Work Session [POST]
To create a new Work Session simply provide a JSON hash of the *start*, *end*, and *note*attributes for the Work Session. 

+ Request (application/json)

        {
            "start": "2014-01-21 11:00",
            "end": "2014-01-21 13:59"
            "note": "I ended because of a phone call"
        }


+ Response 201

    [WorkSession][]